from lsst.meas.base import BasePlugin, wrapSimpleAlgorithm

from .simpleShapeLib import *
from .version import *   # generated by sconsUtils

wrapSimpleAlgorithm(SimpleShape, name="ext_simpleShape_SimpleShape",
        Control=SimpleShapeControl, executionOrder=BasePlugin.SHAPE_ORDER)
